In [4]:
import LogisticRegression as lg
t = lg.LogisticRegressionTest()

In [2]:
lg.LogisticRegressionTest.testF(t)

<type 'numpy.ndarray'>
f complete
[ 3.4657359]
f for first entry


AttributeError: 'numpy.int32' object has no attribute 'dot'

In [3]:
sigmoid = lambda z: 1/(1.0+np.exp(-z))

In [5]:
a = np.ones([2,1])

In [4]:
import numpy as np

In [7]:
a[1]

array([ 1.])

In [8]:
sigmoid(a)

array([[ 0.73105858],
       [ 0.73105858]])

In [9]:
a[1]=0

In [10]:
sigmoid(a)

array([[ 0.73105858],
       [ 0.5       ]])