In [1]:
import numpy as np
import LogisticRegression as lg
t = lg.LogisticRegressionTest()
lg.LogisticRegressionTest.testF(t)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[[0]
 [0]
 [0]
 [0]
 [0]]
f complete
[[ 7.00091147]
 [ 7.00091147]
 [ 6.50150231]
 [ 7.50055293]
 [ 7.00091147]]
f for first entry
[ 7.00091147]
F
7.0009579282
g complete
[[ 4.85534718]
 [ 3.2768562 ]
 [ 1.39867858]
 [ 0.19980852]]


f complete
[[ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]]
f for first entry
[ 0.69314718]
F
[[ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]
 [ 0.69314718]]
g complete
[[ 2.43]
 [ 1.64]
 [ 0.7 ]
 [ 0.1 ]]


In [4]:
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [6]:
y = iris.target[:5,np.newaxis]

In [9]:
y

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [8]:
y.shape

(5L, 1L)

In [8]:
y.shape

(5L,)

In [4]:
print "test %s" % 2

test 2


In [3]:
a

NameError: name 'a' is not defined

In [4]:
a = np.array([[1],[2],[3]])

In [5]:
a.shape

(3L, 1L)

In [6]:
a.flatten

<function flatten>

In [7]:
a.flatten()

array([1, 2, 3])

In [8]:
a.sum()

6

In [9]:
a

array([[1],
       [2],
       [3]])

In [10]:
a.sum()

6